name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: kenvandine/minecraft-server-snap/.github/workflows/reusable-pack-build.yml@main
    with:
      config: pack.yaml
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
